# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc534941b2e5c50538734389ac7b56e12592b80e02beb9e8ac437b4e2d36acc0ce9d9479962106f63bee037a6bf1131d66eb335742dbee40088f4d426d16214b

test:
  secret_key_base: 8f0bc47a076b8423f7a02c5e06fe84fad8b401969ac44f8d53f46d67da6c2be32b15ca21eabf742750f58696df9e702fc6f6d9586f0afe1e5f185598cea34988

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
